apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: myproject
spec:
  ports:
    - port: 8181
      protocol: TCP
      targetPort: 8080
  selector:
    app: myrepo
  sessionAffinity: None
  type: ClusterIP
